### ISSUE TITLE
PEP images not getting created, permissions issue

### ISSUE THREAD

**Issue by frankwiles** [python/psf-chef#146]
Hi! 

Ok so in reference to this Python.org ticket (https://github.com/python/pythondotorg/pull/505) PEP images still aren't displaying.  

I believe it's because /srv/redesign.python.org/shared/media is owned root:root and cannot be written to by www-data which is what the cron and app code runs as.  I'm honestly surprised an exception isn't raised when this happens, but apparently it isn't.  Can we get this fixed asap?

**Comment by gutworth** [comment]
Is this okay on the new infra?

**Comment by frankwiles** [comment]
Yep perms are fine on staging and prod in salt/rackspace.  The issue is in the code/movement of the data now I believe which is in my court.  Thanks!
