### ISSUE TITLE
Today's mess, need access to fix

### ISSUE THREAD

**Issue by frankwiles** [python/psf-chef#147]
Hey, 

So I'm guessing that prod got moved to a new box? Perhaps pydotorg-prod.iad1.psf.io or lb0.iad1.psf.io?
I no longer have access to this box (user frank) and can't fix the migration issue. 

I was working on virt-q0dzqq.psf.osuosl.org (prod) and virt-l4es2w.psf.osuosl.org (stage) and it took me forever to figure out why the site worked fine directly, but not via Fastly. 

So site is broken, fix that worked on old prod was: 

1) Comment up 'peps' app in INSTALLED_APPS 
2) Run migrations 
3) Uncomment 'peps' app.

**Comment by gutworth** [comment]
python/psf-salt@a78960407a752f0adb5ac7104f7619453a0e76d0
